### ISSUE TITLE
Return proper HTTP codes

### ISSUE THREAD

**Issue by cippaciong** [middleware2018-PSS/Services#4]
Many methods don't return the proper HTTP code. We will use this issue to list those methods and mark them as solved once they are fixed.
### Accounts
- [ ] `PUT /accounts` made by unauthorized users return *406 Not Acceptable* instead of *403 Forbidden*
- [ ] `GET /accounts` made by unauthorized users returns *204 No Content* instead of *403 Forbidden* or a list containing only themselves (for users that are not admins)

**Comment by phisco** [comment]
RIP
